Repository lapi-hotel-group/furport-front, pull requests merged in 2020-08, with the labels that each got.

#174 Feature/add datetime sort
  src/components/Events/Sort.js
  src/containers/Events/Events.js
Labels: enhancement

#182 feat: add online locations
  src/components/Events/EventCard.js
  src/components/Events/EventDetail.js
  src/components/Events/EventForm.js
  src/components/Events/EventTable.js
  src/components/Statistics/AreaPieChart.js
  src/containers/Events/Events.js
  src/utils/csc.js
  src/utils/locations/city.json
  src/utils/locations/country.json
  src/utils/locations/state.json
Labels: enhancement

#183 Release/v0.2.2
  package-lock.json
  package.json
  src/components/Events/EventCard.js
  src/components/Events/EventDetail.js
  src/components/Events/EventForm.js
  src/components/Events/EventTable.js
  src/components/Events/Sort.js
  src/components/Footer/Footer.js
  src/components/Statistics/AreaPieChart.js
  src/containers/Events/Events.js
  src/utils/csc.js
  src/utils/locations/city.json
  src/utils/locations/country.json
  src/utils/locations/state.json
  yarn.lock
Labels: release

#184 fix: update version
  package.json
  src/components/Footer/Footer.js
Labels: release

#189 Feature/call new event by url query
  src/components/Events/.EventForm.js.swp
  src/components/Events/EventEdit.js
  src/components/Events/EventForm.js
  src/components/Events/EventTable.js
  src/components/Events/NewEvent.js
  src/containers/Events/Events.js
Labels: enhancement

#191 Use package.json version for footer
  src/components/Footer/Footer.js
Labels: enhancement

#193 Update lint.yml
  .github/workflows/lint.yml
Labels: enhancement

#200 Release/v0.2.3
  .github/workflows/lint.yml
  .github/workflows/reviewdog.yml
  package-lock.json
  package.json
  src/components/Dashboard/NextEvent.js
  src/components/Dashboard/RecentEvents.js
  src/components/Events/.EventForm.js.swp
  src/components/Events/DeleteButton.js
  src/components/Events/EventEdit.js
  src/components/Events/EventForm.js
  src/components/Events/EventTable.js
  src/components/Events/NewEvent.js
  src/components/Events/NewTag.js
  src/components/Footer/Footer.js
  src/components/Home/ChangeLog.js
  src/components/Settings/ChangePassword.js
  src/containers/Events/Events.js
  src/containers/Login/Login.js
  src/containers/Register/Register.js
  yarn.lock
Labels: release

#201 update: update version
  package.json
Labels: release

#207 Show same event modal
  src/components/Events/EventForm.js
  src/components/Events/SameEventModal.js
Labels: enhancement

#208 feat: show modal when close eventform
  src/components/Events/CloseFormModal.js
  src/components/Events/EventEdit.js
  src/components/Events/NewEvent.js
Labels: enhancement

#209 Get changelog from GitHub releases
  .github/workflows/deploy-release.yml
  src/components/Home/ChangeLog.js
  src/releases.json
Labels: enhancement

#211 Release/v0.2.4
  .github/workflows/deploy-release.yml
  package-lock.json
  package.json
  src/components/Events/CloseFormModal.js
  src/components/Events/EventEdit.js
  src/components/Events/EventForm.js
  src/components/Events/NewEvent.js
  src/components/Events/SameEventModal.js
  src/components/Home/ChangeLog.js
  src/components/Users/Achievements.js
  src/containers/About/Terms.js
  src/i18n.js
  src/locales/en.json
  src/locales/ja.json
  src/releases.json
Labels: release

#212 Release/v0.2.4
  package.json
Labels: release

#214 feat: update-timezone-handling
  package-lock.json
  package.json
  src/components/Events/EventCard.js
  src/components/Events/EventDetail.js
  src/components/Events/EventForm.js
  src/components/Events/EventTable.js
Labels: enhancement

#215 feat: add issues and prs template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#216 Release/v0.3.0
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/components/Events/EventCard.js
  src/components/Events/EventDetail.js
  src/components/Events/EventForm.js
  src/components/Events/EventTable.js
Labels: release

#217 Release/v0.3.0
  package.json
Labels: release

#219 fix: fix date format of eventCard
  src/components/Events/EventCard.js
Labels: bug

#223 Feature/no time flag
  docs/docs/how-to-create-event.md
  src/components/Events/EventCard.js
  src/components/Events/EventDetail.js
  src/components/Events/EventForm.js
  src/components/Events/EventTable.js
Labels: enhancement

#225 Release/v0.3.1
  package.json
Labels: release

#227 feat: Add Typescript Settings
  .eslintrc.js
  package-lock.json
  package.json
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: enhancement

#238 Release/v0.3.3
  .github/old/deploy-release.yml
  .github/old/deploy-stg.yml
  README.md
  docs/docusaurus.config.js
  package.json
  public/_redirects
  src/components/Events/NewEvent.tsx
  src/components/Footer/Footer.js
  src/containers/Users/.UserProfile.js.swp
Labels: release

#239 Release/v0.3.3
  README.md
  package.json
Labels: release

#257 add: documentation for i18n
  docs/docs/dev/i18n/folder-structure.md
  docs/docs/dev/i18n/how-to-translate.md
  docs/docs/dev/i18n/namespace.md
  docs/docs/dev/i18n/naming-convention-for-key.md
  docs/sidebars.js
Labels: documentation

#260 Release/v0.3.4
  package.json
Labels: release
